### PR TITLE
Sign bundles published from archives and during copy

### LINKED ISSUE #3201: Bundle is not signed when pushed from an archive
## Describe the bug
When pushing a bundle from an archive the resulting bundle is not signed when the `--sign-bundle` flag is passed, and no warning or error is shown.

## To Reproduce
1. Run `porter publish --sign-bundle --archive <ARCHIVE> --reference <REFERENCE>`
4. Looking in the repository the bundle and invocation image is not signed

## Expected behavior
The bundle and invocation image should be signed

### LINKED ISSUE #3203: Copying bundles doesn't support signing
## Describe the bug
When copying a bundle between repositories, it is not possible to have the destionation bundle signed.

## To Reproduce
1. Run `porter copy --source <SOURCE> --destination <DEST>` where `<SOURCE>` is a signed bundle
2. See that the destination bundle is not signed, even if the source bundle is signed

## Expected behavior
The destination bundle is signed, or it is possible to create a new signature for the destination bundle

### PR DESCRIPTION
**Pull request by kichristensen**
# What does this change
Support signing and verifying bundles published from archives.
Also adds support for signing bundles during copy

This is handle by creating a new signature, NOT by copying the potential existing signature. This is done for two reasons:
1. A signature might not be present on the source bundle
1. Repositories might use different digest algorithms or calculate the digest differently

# What issue does it fix
Closes #3201 
Closes #3203 

# Notes for the reviewer
_Put any questions or notes for the reviewer here._

# Checklist
- [X] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

[contributors]: https://porter.sh/src/CONTRIBUTORS.md

### CODE REVIEW

File: pkg/porter/copy.go [hunk 1]
```diff
@@ -98,9 +99,27 @@ func (p *Porter) CopyBundle(ctx context.Context, opts *CopyOpts) error {
...
 	bunRef.Reference = destinationRef
 
-	_, err = p.Registry.PushBundle(ctx, bunRef, regOpts)
+	bunRef, err = p.Registry.PushBundle(ctx, bunRef, regOpts)
 	if err != nil {
 		return span.Error(fmt.Errorf("unable to copy bundle to new location: %w", err))
 	}
+
+	if opts.SignBundle {
+		for _, invImage := range bunRef.Definition.InvocationImages {
```
Comment (schristoff) [inline pkg/porter/copy.go:108]: The s/InvocationImages/BundleImage is going to be going on for awhile - but I'm not gonna nit over that. Just a comment.

Comment (kichristensen) [reply pkg/porter/copy.go:108]: Ahh yes, good point. Changed it anyway, to make sure it is not forgotten
