### PR TITLE
staticcheck lint fixes

### LINKED ISSUE #2081: Resolve lint and vet errors
Once we have lint and vet targets from #2080, we need to identify which lint rules we want to follow. Not all will make sense for our project and desired coding style. So some may end up being ignored via staticcheck's [config](https://staticcheck.io/docs/configuration/) file.

Whoever grabs this should try to fix what makes sense, and then if the required fixes for some parts doesn't make the code better or makes it hard to read, then ignore those rules.

I don't think vet is configurable so we will need to just fix all of those.

See our [Contributing Tutorial](https://release-v1.porter.sh/contribute/tutorial) and [New Contributor Guide](https://github.com/getporter/porter/blob/release/v1/CONTRIBUTING.md) for help getting started contributing to Porter.

### PR DESCRIPTION
**Pull request by tchaudhry91**
# What does this change
A bunch of staticcheck fixes that I felt were straightforward. Some maybe debatable and can be "ignored" or worked around. Those can be discussed in the PR.

# What issue does it fix
#2081 - Incremental Progress

# Notes for the reviewer
Some fairly straightforward things unchecked errors etc have been fixed. A couple of potential bugs as well (checking err instead of !ok).

# Checklist
- [ ] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://porter.sh/src/CONTRIBUTORS.md

### CODE REVIEW

File: pkg/cache/cache_test.go [hunk 1]
```diff
@@ -181,6 +181,7 @@ func TestStoreRelocationMapping(t *testing.T) {
 			assert.Equal(t, tc.wantedReloPath, cb.RelocationFilePath, "didn't get expected path for store")
 
 			cb, _, err = c.FindBundle(tc.tag)
+			assert.NoError(t, err, fmt.Sprintf("didn't expect find bundle error for test %s", tc.tag))
```
Comment (carolynvs) [inline pkg/cache/cache_test.go:184]: You don't have to change this but I wanted you to be aware that the assert.NoError function will handle formatting for you. So this line can be simplified to 
```suggestion
			assert.NoError(t, err, "didn't expect find bundle error for test %s", tc.tag)
```

File: pkg/pkgmgmt/client/filesystem.go [hunk 2]
```diff
@@ -45,6 +45,9 @@ type FileSystem struct {
 
 func (fs *FileSystem) List() ([]string, error) {
 	parentDir, err := fs.GetPackagesDir()
+	if err != nil {
+		return nil, errors.Wrap(err, "could not get package directory")
```
Comment (carolynvs) [inline pkg/pkgmgmt/client/filesystem.go:49]: Can you switch this to use fmt.Errorf and the "%w" placeholder instead of the pkg/errors package? We are trying to stop using the errors package (#2009).

File: pkg/pkgmgmt/feed/generate.go [hunk 3]
```diff
@@ -167,6 +167,9 @@ func (feed *MixinFeed) Save(opts GenerateOptions) error {
 	tmplData["Updated"] = entries[0].Updated()
 
 	atomXml, err := mustache.Render(string(feedTmpl), tmplData)
+	if err != nil {
+		return errors.Wrap(err, "error rendering template")
```
Comment (carolynvs) [inline pkg/pkgmgmt/feed/generate.go:171]: Can you use fmt.Errorf + "%w" instead of the errors package here?

File: pkg/porter/upgrade.go [hunk 4]
```diff
@@ -72,6 +72,9 @@ func (p *Porter) UpgradeBundle(ctx context.Context, opts UpgradeOptions) error {
 	}
 
 	err = p.applyActionOptionsToInstallation(ctx, &i, opts.BundleActionOptions)
+	if err != nil {
+		return errors.Wrap(err, "could not apply options to installation")
```
Comment (carolynvs) [inline pkg/porter/upgrade.go:76]: Can you use fmt.Errorf + "%w" instead of the errors package here?

**Review by carolynvs — CHANGES_REQUESTED** [review]
Looks good! I just have a couple small changes that need to be made and this is ready to merge.

**Comment by tchaudhry91** [comment]
@carolynvs completed changes as requested!

**Review by carolynvs — APPROVED** [review]
Thanks for cleaning up all the lint errors! This is really helpful and we can finally enforce no lint errors going forward in our builds. 💪

**Comment by tchaudhry91** [comment]
Hehe. Thanks @carolynvs but there are a few staticcheck fixes still left before we enforce lint in the CI. The remaining changes may require your input though or atleast I felt like there was something not totally straightforward with those.

**Comment by carolynvs** [comment]
@tchaudhry91 oops, I must have missed that. Are we tracking that problem in another issue or pull request?

**Comment by tchaudhry91** [comment]
@carolynvs we can track it in #2081 only. I'll update it with the remaining fixes.
