### PR TITLE
Fix performance for porter list

### LINKED ISSUE #2040: porter list should not make individual calls for each installation
After I instrumented the plugins, I found a bug in the list command. We are calling out to the database and the secrets plugin for each installation returned by list.

Screen Shot 2022-04-27 at 10 34 00 AM

That entire long tail of calls to storage and secrets should not be there. We should only make enough calls to display the information required for `porter list --output plaintext`. This means that even though the json/yaml outputs _could theoretically_ provide more information, we shouldn't make extra calls to grab that info.

I'm not sure why yet that we are making all these calls, they are appropriate for `porter installation show` for example, but for a list command the performance / chattiness is a problem. I'm guessing we are retrieving the latest run for each installation? If needed we can optimize how we are retrieving the data so that it's a single call to installations, and then another single call to retrieve all runs, and then join the data in the client.

### PR DESCRIPTION
**Pull request by carolynvs**
# What does this change
Do not retrieve the full installation definition for each installation returned from list. We only need that information
for the show command. Right now porter is making multiple calls to both the storage and secrets plugin for each installation in the list results.

# What issue does it fix
Closes #2040

# Notes for the reviewer
Here is what the trace looks like with this fix (compared to the original trace which was huge)

Screen Shot 2022-05-24 at 3 01 32 PM

# Checklist
- [x] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://porter.sh/src/CONTRIBUTORS.md

### CODE REVIEW

File: pkg/porter/list.go [hunk 1]
```diff
@@ -214,31 +214,32 @@ func NewDisplayRun(run storage.Run) DisplayRun {
...
+		return nil, errors.Wrap(err, "could not list installations")
 	}
 
 	var displayInstallations DisplayInstallations
 	for _, installation := range installations {
-		di, err := p.generateDisplayInstallation(ctx, installation)
-		if err != nil {
-			return err
-		}
+		di := NewDisplayInstallation(installation)
```
Comment (carolynvs) [inline pkg/porter/list.go:228]: I moved the conversion of installations to display installations so that we could test these functions. In other parts of Porter we do the same thing but I guess this function is old enough it was doing the conversion in the print function still.

File: pkg/porter/show.go [hunk 2]
```diff
@@ -163,27 +171,23 @@ func (p *Porter) ShowInstallation(ctx context.Context, opts ShowOptions) error {
...
 }
 
-func (p *Porter) generateDisplayInstallation(ctx context.Context, installation storage.Installation) (DisplayInstallation, error) {
-	run, err := p.Installations.GetRun(ctx, installation.Status.RunID)
-	if err != nil {
-		return DisplayInstallation{}, err
-	}
-
+func (p *Porter) NewDisplayInstallationWithSecrets(ctx context.Context, installation storage.Installation, run *storage.Run) (DisplayInstallation, error) {
 	bun := cnab.ExtendedBundle{run.Bundle}
```
Comment (VinozzZ) [inline pkg/porter/show.go:175]: What if the run is nil here?

Comment (carolynvs) [reply pkg/porter/show.go]: Haha you caught that at the same time I did, I was fixing that right before our meeting this morning. I just pushed it up now.

**Comment by carolynvs** [comment]
@VinozzZ Okay I think I've fixed everything, please take another look!

**Review by VinozzZ — APPROVED** [review]
