### PR TITLE
Use a custom extension for File type

### LINKED ISSUE #1417: Porter explain shows string when the parameter is of type file
## Describe the bug
Porter has a custom parameter type of file, that is actually a string parameter in the bundle.jon. The porter explain command is showing string instead of file for the parameter type.

## To Reproduce
```console
$ porter explain --tag ghcr.io/squillace/aks-kubeflow:v0.3.0
Name: aks-kubeflow
Description: A bundle that installs, tests, and uninstalls Kubeflow on AKS. It currently requires an Azure Service Principal with the following role scoped to the AKS service instance: az ad sp create-for-rbac -n "kubeconfig-read" --role "Azure Kubernetes Service Cluster User Role" --scopes <cluster resource id>
Version: 0.3.0
Credentials:
Name                    Description                                                                        Required
AZURE_CLIENT_ID         The client id for the service principal used to automate the bundle's actions.     true
AZURE_SP_PASSWORD       The service principal password that is used to log into Azure inside the bundle.   true
AZURE_SUBSCRIPTION_ID   The Azure subscription into which to deploy.                                       true
TENANT_ID_OR_DNS        The tenant identity in which the service principal resides.                        true
Parameters:
Name                   Description                                     Type     Default                   Required   Applies To
AZURE_RESOURCE_GROUP   The Azure resource group for the AKS cluster.   string   <nil>                     true       All Actions
CLUSTER_NAME           The name of the AKS cluster.                    string   <nil>                     true       All Actions
CONFIG_FILE            The deployment config file used for kfctl.      string   kfctl_azure.v1.2.0.yaml   false      All Actions
KF_DIR                 The deployment folder used for kfctl.           string   v1.2-deployment           false      All Actions
kustomize                                                              string   <nil>                     true       uninstall
```

Note that kustomize is a file parameter.

## Expected behavior
It should say the type is file not string.

## Porter Command and Output
(above)

## Version

v0.30.1

### PR DESCRIPTION
**Pull request by carolynvs**
# What does this change
Previously we had checks throughout the codebase checking if a parameter is Porter's special "file" type. Which lead to #1417 where `porter explain` shows the underlying string type for a file parameter instead of "file".

I have made the file type a custom extension under the porter namespace, and centralized the logic for the parameter type. I will submit this to the CNAB spec as a well-known extension since I think it is useful beyond Porter.

I also made our extension constants consistent.

# What issue does it fix
Fixes #1417 

# Notes for the reviewer
Sorry this isn't split up into two commits! 😝 

# Checklist
- [x] Unit Tests
- [ ] Documentation
- [ ] Schema (porter.yaml)

If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

[contributors]: /CONTRIBUTORS.md

### CODE REVIEW

**Comment by carolynvs** [comment]
@vdice This is now ready for review.

File: pkg/cnab/extensions/file_parameter.go [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+	if SupportsExtension(b, FileParameterExtensionKey) {
+		return true
+	}
+
+	// Porter has always supported this but didn't have the extension declared
+	// TODO(v1): Remove this logic in v1.0?
+	return IsPorterBundle(b)
+}
+
+// FileParameterSupport checks if the docker extension is present and returns its
```
Comment (vdice) [inline pkg/cnab/extensions/file_parameter.go:41]:
```suggestion
// FileParameterSupport checks if the file parameter extension is present
```

File: pkg/cnab/extensions/file_parameter.go [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+// extension configuration.
```
Comment (vdice) [inline pkg/cnab/extensions/file_parameter.go:42]: Depending on updated verbiage above, this line can be removed

File: pkg/cnab/extensions/dependencies_test.go [hunk 3]
```diff
@@ -85,3 +85,49 @@ func TestDependencies_ListBySequence(t *testing.T) {
...
+		b := bundle.Bundle{}
+
+		assert.False(t, SupportsDependencies(b))
+	})
+}
+
+func TestHasDependencies(t *testing.T) {
+	t.Parallel()
+
+	t.Run("has parameter sources", func(t *testing.T) {
```
Comment (vdice) [inline pkg/cnab/extensions/dependencies_test.go:116]: nit: test name should mentioned dependencies instead, right?

File: pkg/cnab/extensions/dependencies_test.go [hunk 4]
```diff
@@ -85,3 +85,49 @@ func TestDependencies_ListBySequence(t *testing.T) {
...
+		b := bundle.Bundle{
+			RequiredExtensions: []string{DependenciesExtensionKey},
+			Custom: map[string]interface{}{
+				DependenciesExtensionKey: struct{}{},
+			},
+		}
+
+		assert.True(t, HasDependencies(b))
+	})
+	t.Run("no parameter sources", func(t *testing.T) {
```
Comment (vdice) [inline pkg/cnab/extensions/dependencies_test.go:126]: nit: test name should mentioned dependencies instead, right?

File: pkg/porter/outputs.go [hunk 5]
```diff
@@ -110,11 +112,9 @@ func NewDisplayOutputs(outputs claim.Outputs, format printer.Format) DisplayOutp
 		if err != nil {
 			continue
 		}
-		do.Type = outputType
 
-		// Try to figure out if this was originally a file output. Long term, we should find a way to find
-		// and crack open the invocation image to get the porter.yaml
-		if do.Type == "string" && schema.ContentEncoding == "base64" {
+		do.Type = outputType
```
Comment (vdice) [inline pkg/porter/outputs.go:116]: Can/should we use `outputType := extensions.GetParameterType(bun, schema)` above such that lines 117-119 below are no longer needed?

**Review by vdice — COMMENTED** [review]
So many improvements in this PR! Only a few comments/questions.

File: pkg/cnab/extensions/dependencies_test.go [hunk 6]
```diff
@@ -85,3 +85,49 @@ func TestDependencies_ListBySequence(t *testing.T) {
...
+	t.Run("supported", func(t *testing.T) {
+		b := bundle.Bundle{
+			RequiredExtensions: []string{DependenciesExtensionKey},
+		}
+
+		assert.True(t, SupportsDependencies(b))
+	})
+	t.Run("supported-shorthand", func(t *testing.T) {
+		b := bundle.Bundle{
+			RequiredExtensions: []string{DependenciesExtensionKey},
```
[the remark this answers is not in the document]
Comment (carolynvs) [reply pkg/cnab/extensions/dependencies_test.go:101]: oops!

File: pkg/cnab/extensions/extensions.go [hunk 7]
```diff
@@ -0,0 +1,23 @@
...
+	PorterExtensionsPrefix = "sh.porter."
+
+	// OfficialExtensionsPrefix is the prefix applied to extensions defined in the CNAB spec.
+	OfficialExtensionsPrefix = "io.cnab."
+)
+
+// SupportsExtension checks if the bundle supports the specified CNAB extension.
+func SupportsExtension(b bundle.Bundle, key string) bool {
+	for _, key := range b.RequiredExtensions {
+		if key == key {
```
[the remark this answers is not in the document]
Comment (carolynvs) [reply pkg/cnab/extensions/extensions.go:18]: *grumble* I don't know what I was on when I wrote that line.

**Comment by carolynvs** [comment]
I have created an [issue](https://github.com/cnabio/cnab-spec/issues/403) to track the inconsistent spec around the dependencies key. Porter writes it has the fully `io.cnab.dependencies` and we shouldn't be matching on the shorthand as that can have false positives.

**Comment by carolynvs** [comment]
Here's the PR to clarify the spec: https://github.com/cnabio/cnab-spec/pull/404

**Review by vdice — APPROVED** [review]
LGTM!
