### PR TITLE
Lint messages reported from porter should not mention mixins

### LINKED ISSUE #2526: Lint messages reported from porter should not mention mixins
When porter generates a lint message directly, instead of the message coming from a mixin, we should change the message so that it doesn't print out extra "empty" text about mixins that isn't relevant.

Once #2434 is merged, you can do the following to reproduce:

1. porter create
2. edit porter.yaml and define a parameter named "porter_test"
3. porter lint

expected output
```
Running linters for each mixin used in the manifest...
error(porter-100) - Reserved name warning
porter_test has a reserved prefix. Parameters cannot start with porter- or porter_
See https://getporter.org/reference/linter/#porter-100 for more information
```

actual output
```
Running linters for each mixin used in the manifest...
error(porter-100) - Reserved name warning
: 0th step in the  mixin ()
porter_test has a reserved prefix. Parameters cannot start with porter- or porter_
See https://getporter.org/reference/linter/#porter-100 for more information
```

You can tell that a lint result was generated by porter because Location.Mixin is an empty string. The relevant code to change is 

https://github.com/getporter/porter/blob/6df27907b5a40482ceb8c036fede2fa56a518c16/pkg/linter/linter.go#L113-L116

Please update the unit tests in linter_test.go to validate that lint results generated by porter do not print out that extra text ": 0th step in the  mixin ()"

See our [Contributing Tutorial](https://getporter.org/contribute/tutorial) and [New Contributor Guide](https://github.com/getporter/porter/blob/release/v1/CONTRIBUTING.md) for help getting started contributing to Porter.

### PR DESCRIPTION
**Pull request by kichristensen**
# What does this change
When porter generates a lint message directly, instead of the message coming from a mixin, we should change the message so that it doesn't print out extra "empty" text about mixins that isn't relevant.

# What issue does it fix
Closes #2526

# Notes for the reviewer
There is a stale PR, #2530, for the same issue.

# Checklist
- [X] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [X] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

### CODE REVIEW

File: pkg/linter/linter.go [hunk 1]
```diff
@@ -111,8 +111,12 @@ type Location struct {
 }
 
 func (l Location) String() string {
-	return fmt.Sprintf("%s: %s step in the %s mixin (%s)",
-		l.Action, humanize.Ordinal(l.StepNumber), l.Mixin, l.StepDescription)
+	mixin := ""
```
Comment (schristoff) [inline pkg/linter/linter.go:114]: Looking at the original issue, I think the logic should be something along the lines of if the mixin name is "", we should not be returning a string. Let me know if you are reading that from #2526

Comment (kichristensen) [reply pkg/linter/linter.go:114]: You are complety correct, I will work on the change

Comment (kichristensen) [reply pkg/linter/linter.go]: @schristoff It has been changed now to align with your comment

**Review by schristoff — APPROVED** [review]
