### PR TITLE
stop using unsupported debug flag for plugins

### LINKED ISSUE #2375: Unable to install v1.0.0-rc.1 plugins
## Describe the bug

when installing the newly release v1.0.0-rc.1 plugins, porter fails with exit status 1

It looks like it's due to the removal of the `--debug` in plugins. If porter stop sending the `--debug` flag when it query plugin version, it should fix it

## To Reproduce
1. Run `Porter plugins install kubernetes -v v1.0.0-rc.1`
```
Downloading https://cdn.porter.sh/plugins/atom.xml to /var/folders/mv/cx7sy9c54wn741p4x6v0_t100000gn/T/porter598642588/atom.xml

kubernetes @ v1.0.0-rc.1 did not publish a download for darwin/arm64, falling back to darwin/amd64
Downloading https://cdn.porter.sh/plugins/kubernetes/v1.0.0-rc.1/kubernetes-darwin-amd64 to /Users/carolynvs/.porter/plugins/kubernetes/kubernetes

Downloading https://cdn.porter.sh/plugins/kubernetes/v1.0.0-rc.1/kubernetes-linux-amd64 to /Users/carolynvs/.porter/plugins/kubernetes/runtimes/kubernetes-runtime

exit status 1
exit status 1
exit status 1
```

## Expected behavior
porter should successfully install the plugins

## Version
porter v1.0.0-rc.2

### PR DESCRIPTION
**Pull request by VinozzZ**
# What does this change

since porter has removed the debug flag from plugins, we need to remove the reference in porter when running a plugin command

# What issue does it fix
Closes #2375 

# Notes for the reviewer

# Checklist
- [ ] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://getporter.org/src/CONTRIBUTORS.md

### CODE REVIEW

File: pkg/porter/plugins.go [hunk 1]
```diff
@@ -158,7 +158,7 @@ func (p *Porter) InstallPlugin(ctx context.Context, opts plugins.InstallOptions)
 
 	plugin, err := p.Plugins.GetMetadata(ctx, opts.Name)
 	if err != nil {
-		return err
+		return fmt.Errorf("failed to get plugin metadata: %w", err)
```
Comment (carolynvs) [inline pkg/porter/plugins.go:161]: By the way, I created https://github.com/getporter/porter/issues/2376 to improve the error message returned when calls to the plugin fail. It would have helped us debug if stderr had been included in the error message that was returned in err.

**Review by carolynvs — APPROVED** [review]
LGTM
