### PR TITLE
Validate reserved names

### LINKED ISSUE #1226: Validate that the author didn't use reserved parameter names during porter lint
Porter has reserved parameter names, for example `porter-debug`, that authors can't use for their own bundles. We should check that the author didn't use any reserved names that would collide with our own naming conventions for parameters, outputs, etc during `porter lint` and hard fail.

### PR DESCRIPTION
**Pull request by Simpcyclassy**
# What does this change
This PR checks for reserved names in porter and fails lint check if user used a bundle name that already exists

# What issue does it fix
Closes #1226 

# Notes for the reviewer

# Checklist
- [x] Did you write tests?
- [x] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://getporter.org/src/CONTRIBUTORS.md

### CODE REVIEW

**Comment by carolynvs** [comment]
@Simpcyclassy Thanks for picking up this issue! When you are ready for a review, click the "Ready for Review" button.

You will also need to sign your commit, you can learn more here: https://getporter.org/contribute/guide/#signing-your-commits

If you can sign them all great, otherwise just sign one of them and I'll handle consolidating your commits into a single signed commit when I merge the PR.

**Comment by Simpcyclassy** [comment]
Hey, @carolynvs we looked at this issue again today and spent some time looking without success for where we could find a list of the reserved parameters on porter. We wondered if it would be okay to create a config file to list the parameters and how to get a list of all the parameters. Can you help us?

I have not been able to fix the pipeline as well.

**Comment by carolynvs** [comment]
Sorry about that, the "Security Scan / scan (pull_request_target)" pipeline was broken for a while on main but has since been fixed. You can ignore the error, or if you merge main into your branch, that should fix that pipeline.

We don't have a list of reserved words but we do have a reserved prefix, if a credential, parameter or state variable name in porter.yaml starts with "porter-" or "porter_" (case-insensitive, so you can force it to lowercase and then compare), then the variable should be considered reserved and an error returned from the lint command.

File: pkg/linter/linter.go [hunk 1]
```diff
@@ -152,10 +152,38 @@ func New(cxt *portercontext.Context, mixins pkgmgmt.PackageManager) *Linter {
...
+				res := Result {
+					Level: LevelWarning,
+					Location: Location {
+						Action: "",
+						Mixin: "",
+						StepNumber: 0,
+						StepDescription: "",
+				
+					},
+					Code: "exec-100",
```
Comment (carolynvs) [inline pkg/linter/linter.go:178]: Let's give this one a unique code, `porter-100` so that it doesn't get confused with lint results returned from the exec mixin.

File: pkg/linter/linter.go [hunk 2]
```diff
@@ -152,10 +152,38 @@ func New(cxt *portercontext.Context, mixins pkgmgmt.PackageManager) *Linter {
...
+					Title: "Reserved name warning",
+					Message: param.Name + " has a reserved prefix",
```
Comment (carolynvs) [inline pkg/linter/linter.go:180]: Let's give the user a bit more information in the message so that they understand why their name isn't okay.

```suggestion
					Message: param.Name + " has a reserved prefix. Parameters cannot start with porter- or porter_",
```

File: pkg/linter/linter.go [hunk 3]
```diff
@@ -152,10 +152,38 @@ func New(cxt *portercontext.Context, mixins pkgmgmt.PackageManager) *Linter {
...
+					URL: "",
```
Comment (carolynvs) [inline pkg/linter/linter.go:181]: I've created another issue that builds off of what you have done here. #2486 Feel free to take that issue once you are finished with this pull request if you are interested!

File: pkg/linter/linter.go [hunk 4]
```diff
@@ -152,10 +152,38 @@ func New(cxt *portercontext.Context, mixins pkgmgmt.PackageManager) *Linter {
 	}
 }
 
+
 func (l *Linter) Lint(ctx context.Context, m *manifest.Manifest) (Results, error) {
 	// TODO: perform any porter level linting
 	// e.g. metadata, credentials, properties, outputs, dependencies, etc
+	reservedPrefixes := []string{"porter-", "porter_"}
```
Comment (carolynvs) [inline pkg/linter/linter.go:159]: Let's change the comment above to remove the TODO since you have implemented a lint check now for porter. Can you instead leave a short comment about what you are checking for (the reserved porter prefix on parameter names)?

This will make it easier for people to figure out what we are checking for as we add more lint checks over time.

File: pkg/linter/linter_test.go [hunk 5]
```diff
@@ -72,4 +72,105 @@ func TestLinter_Lint(t *testing.T) {
...
+			},
+		}
+
+		results, err := l.Lint(ctx, m)
+		require.NoError(t, err, "Lint failed")
+		require.Len(t, results, 1, "linter should have returned 1 result")
+		require.Equal(t, mixins.LintResults, results, "unexpected lint results")
+	})
+
+	t.Run("is case insensitive and does not use reserved prefix even if mixed case or upper", func(t *testing.T) {
```
Comment (carolynvs) [inline pkg/linter/linter_test.go:112]: You do not need to change your tests here unless you want to try it out; Your tests work fine. But I'd like to share a way to have the same number of test cases with a bit less copy/paste code.

Here's an example of how to create testcases or a test matrix. The testcase contains unique inputs for the testcase, such as the parameter name and if we expect an error or not.

Then the code creates a new subtest for each test cases and uses the testcase data structure to validate that test case.

https://github.com/getporter/porter/blob/138f83d0a2568feb5ff279724ed543f1fd0bbe6f/pkg/porter/parameters_test.go#L456

If you search the codebase for `testcases :=` you will find a lot more examples that you can use to get familiar with this way of writing tests in Go.

**Review by carolynvs — CHANGES_REQUESTED** [review]
This is looking good. I've included some suggested changes that will help us maintain this better over time.

File: pkg/linter/linter.go (hunk 3 above)
Comment (carolynvs) [reply pkg/linter/linter.go:181]: Nevermind, someone else asked to work on that issue. But once they are done we will need to add your new lint error to the page that they create.

**Comment by carolynvs** [comment]
I have created follow-up issues based on other bugs I found when testing the PR:

* https://github.com/getporter/porter/issues/2525
* https://github.com/getporter/porter/issues/2526

**Comment by carolynvs** [comment]
@Simpcyclassy Your unit test, `TestLinter_Lint`, is failing because it still needs to be updated with the new lint result level (it should be an error now and not a warning).

File: docs/content/reference/linter.md [hunk 6]
```diff
@@ -15,3 +17,15 @@ Using embedded Bash scripts can be problematic because they can be difficult to
 To fix the problem indicated by the exec-100 warning, you can try replacing any embedded Bash scripts in your exec mixins with scripts.
 
 You can find more information about best practices for using the exec mixin on the Porter website at the following URL: https://getporter.org/best-practices/exec-mixin/#use-scripts.
+
+
+## porter-100
+The porter-100 warning is a message generated by the porter lint command when it detects when a  parameter name has one of the reserved prefixes `porter-` and `porter_`.
```
Comment (carolynvs) [inline docs/content/reference/linter.md:23]:
```suggestion
The porter-100 error is a message generated by the porter lint command when it detects when a  parameter name has one of the reserved prefixes `porter-` and `porter_`.
```

File: docs/content/reference/linter.md [hunk 7]
```diff
@@ -15,3 +17,15 @@ Using embedded Bash scripts can be problematic because they can be difficult to
...
+
+The porter-100 warning suggests that a pararmeter has been created which uses one of the reserved prefixes.
```
Comment (carolynvs) [inline docs/content/reference/linter.md:25]:
```suggestion
The porter-100 error suggests that a parameter has been created which uses one of the reserved prefixes.
```

File: docs/content/reference/linter.md [hunk 8]
```diff
@@ -15,3 +17,15 @@ Using embedded Bash scripts can be problematic because they can be difficult to
...
+
+Using a reserved prefix can be problematic as it can overwrite a predefined parameter resulting in undeterministic behaviour.
+
+To fix the problem indicated by the porter-100 warning, you can try replacing the prefix of any newly defined parameters.
```
Comment (carolynvs) [inline docs/content/reference/linter.md:29]:
```suggestion
To fix the problem indicated by the porter-100 error, you should replace the prefix of any newly defined parameters to not start with "porter".
```

File: pkg/linter/linter.go [hunk 9]
```diff
@@ -152,10 +152,37 @@ func New(cxt *portercontext.Context, mixins pkgmgmt.PackageManager) *Linter {
...
+					Level: LevelError,
+					Location: Location {
+						Action: "",
+						Mixin: "",
+						StepNumber: 0,
+						StepDescription: "",
+				
+					},
+					Code: "porter-100",
+					Title: "Reserved name warning",
```
Comment (carolynvs) [inline pkg/linter/linter.go:178]:
```suggestion
					Title: "Reserved name error",
```

File: pkg/linter/linter_test.go [hunk 10]
```diff
@@ -72,4 +72,85 @@ func TestLinter_Lint(t *testing.T) {
...
+					Level: LevelError,
+					Location: Location {
+						Action: "",
+						Mixin: "",
+						StepNumber: 0,
+						StepDescription: "",
+				
+					},
+					Code: "porter-100",
+					Title: "Reserved name warning",
```
Comment (carolynvs) [inline pkg/linter/linter_test.go:118]:
```suggestion
					Title: "Reserved name error",
```

**Review by carolynvs — CHANGES_REQUESTED** [review]
Looks great, I've found all the text locations where we were still using "warning" instead of "error". Can you try that out and make sure the tests still pass? Then this will be ready to merge.

Thanks!

**Comment by Simpcyclassy** [comment]
Thank you @carolynvs  for catching these and for all the support. I have updated all the use cases.

**Review by carolynvs — APPROVED** [review]
Looks great, thank you for the fix! ✨

**Comment by carolynvs** [comment]
If you are looking for another issue to work on, let me know! I need to go through our backlog again and mark them with help wanted but here are some that I noticed were ready to work on:

https://github.com/getporter/porter/issues/500
https://github.com/getporter/porter/issues/2535
