### PR TITLE
Fix bug where unwanted v is prepended to tag name

### LINKED ISSUE #2914: "v" prefix is prepended to tag when it shouldn't be
## Describe the bug
#2890 introduced a bug which where it appends a "v" prefix where it shouldn't. In the case that the tag is "latest", or when a tag is missing.

## To Reproduce
`porter explain -r ghcr.io/getporter/examples/porter-hello` and 
`bin/porter explain -r ghcr.io/getporter/examples/porter-hello:latest` will try fetch tag :v and :vlatest, respectively

## Expected behavior
No v should be prepended in these cases

## Porter Command and Output
```
$ porter [e.g. install --param foo=bar --credential-set azure]
lots of output
```

## Version
Copy the output of `porter version` below

[e.g. porter v0.14.1-beta.2 (72dd5df)]

### PR DESCRIPTION
**Pull request by ludfjig**
# What does this change
Fixes bug

# What issue does it fix
Closes #2914 

_If there is not an existing issue, please make sure we have context on why this change is needed. See our Contributing Guide for [examples of when an existing issue isn't necessary][1]._

[1]: https://getporter.org/src/CONTRIBUTING.md#when-to-open-a-pull-request

# Notes for the reviewer
_Put any questions or notes for the reviewer here._

# Checklist
- [ ] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://getporter.org/src/CONTRIBUTORS.md

### CODE REVIEW

**Review by schristoff — APPROVED** [review]
gj adding test

**Comment by schristoff** [comment]
if it is telemetry test just merge anyways

File: pkg/porter/lifecycle_test.go [hunk 1]
```diff
@@ -585,7 +586,7 @@ func Test_ensureVPrefix(t *testing.T) {
 				assert.False(t, tt.args.opts._ref.Tag()[0] == 'v')
 			}
 
-			err := ensureVPrefix(tt.args.opts)
+			err := ensureVPrefix(tt.args.opts, os.Stdout)
```
Comment (troy0820) [inline pkg/porter/lifecycle_test.go:589]: Do we need to make all this noise in the test?  Can we use `io.Discard`?

File: pkg/porter/lifecycle_test.go [hunk 2]
```diff
@@ -668,3 +669,53 @@ func Test_ensureVPrefix_idempotent(t *testing.T) {
...
+			BundlePullOptions: BundlePullOptions{
+				Reference:        latestRef,
+				_ref:             nil,
+				InsecureRegistry: false,
+				Force:            false,
+			},
+			bundleRef: nil,
+		}
+
+		err := ensureVPrefix(&opts, os.Stdout)
```
Comment (troy0820) [inline pkg/porter/lifecycle_test.go:690]:
```suggestion
		err := ensureVPrefix(&opts, io.Discard)
```
So we don't have all the noise from the test because we are not asserting against the output.

File: pkg/porter/lifecycle_test.go [hunk 3]
```diff
@@ -668,3 +669,53 @@ func Test_ensureVPrefix_idempotent(t *testing.T) {
...
```
Comment (troy0820) [inline pkg/porter/lifecycle_test.go:715]: Same as above.

File: pkg/porter/lifecycle_test.go [hunk 4]
```diff
@@ -668,3 +669,53 @@ func Test_ensureVPrefix_idempotent(t *testing.T) {
 		})
 	}
 }
+
+// ensure no v is added if specifying :latest tag
+func Test_ensureVPrefix_latest(t *testing.T) {
```
Comment (troy0820) [inline pkg/porter/lifecycle_test.go:674]: Could these be one tests and make the cases a table test? 

```go
tests := map[string]struct{
latestRef string
}{
"latest":{latestRef:"example/porter-hello:latest"},
"not-latest":{latestRef:"example/porter-hello"},
}
for name, test := range tests {
 t.Run(name, func(t *testing.T) {
  opts := BundleReferenceOptions{
			installationOptions: installationOptions{},
			BundlePullOptions: BundlePullOptions{
				Reference:        test.latestRef,
				_ref:             nil,
				InsecureRegistry: false,
				Force:            false,
			},
			bundleRef: nil,
		}
		err := ensureVPrefix(&opts, os.Stdout)
})
}
```

**Review by troy0820 — COMMENTED** [review]
You are facing test failures, outside of this changeset.  These are non-blocking but it would be nice if you could get them in.

File: pkg/porter/lifecycle_test.go (hunk 1 above)
Comment (ludfjig) [reply pkg/porter/lifecycle_test.go:589]: good idea!
