### PR TITLE
Mask sensitive values logged through spans

### LINKED ISSUE #2256: Prevent sensitive data being written to logs/traces
The porter console io.Writer goes through the `CensoredWriter` that ***'s out any sensitive data. Now that we are replacing a lot of printlns with open telemetry traces, and writing to the log file, we need that same censoring for those outputs as well.

Since the TraceLogger is the main way that we print to all 3 now, let's see if we can have the CensoredWriter intercept and rewrite messages there instead of just on the console output.

## Relevant Code
Here is the CensoredWriter that we want to use everywhere to add *** to any sensitive data: https://github.com/getporter/porter/blob/493db3f9d14e686868057669eea6dac6e6c766bf/pkg/portercontext/context.go#L407

* Has a list of registered sensitive words
* When you write to it (io.Writer is what it implements now which may need to change a bit, not sure yet!) it checks for those words and **** them out.

TraceLogger is now the central point where we print to the console, log file or traces. https://github.com/getporter/porter/blob/release/v1/pkg/tracing/traceLogger.go 

* Have each output sink (console, logfile, open telemetry) print **through** the censored writer.

## What to test

* Unit test at the TraceLogger level
* An integration test that makes sure when a "sink" (console, log only) that it gets starred out.

Do not try to test that the traces are being censored, we will make a better [test setup](https://github.com/getporter/porter/blob/release/v1/tests/integration/telemetry_test.go#L23) for that in a separate issue.

# Get Started
See our [Contributing Tutorial](https://release-v1.porter.sh/contribute/tutorial) and [New Contributor Guide](https://github.com/getporter/porter/blob/release/v1/CONTRIBUTING.md) for help getting started contributing to Porter.

### LINKED ISSUE #3216: Sensitive variables printed when exec fails
## Describe the bug
When exec runs with sensitive arguments, and the command returns a bad exit code (e.g. a script or program) it dumps sensitive values in errout. It is not expected that sensitive variables are printed in plain text.

## To Reproduce
Run `porter build && porter install` with the following porter.xml:
```
schemaType: Bundle

schemaVersion: 1.0.1

name: porter-hello

version: 0.1.0

description: "An example Porter configuration"

registry: "localhost:5000"

mixins:
  - exec

parameters:
  - name: secret
    type: string
    default: "---I AM A SECRET VALU1E---"
    sensitive: true

install:
  - exec:
      command: false # /bin/false is a simple way to reproduce, but this could be a program or script.
      arguments:
        - "${bundle.parameters.secret}"
        
upgrade:
  - exec:
      command: true

uninstall:
  - exec:
      command: true
```

## Expected behavior
The sensitive value should **never** be logged out in plain text.

## Porter Command and Output
Cmd:
```
porter build && porter install
```
Output:
```
[ ... build output cut as not relevant ...]
Just-in-time resolving credentials...
Just-in-time resolving parameters...
executing install action from porter-hello (installation: /porter-hello)
error running command /cnab/app /usr/bin/false *******: exit status 1
Error: error running command /cnab/app /usr/bin/false *******: exit status 1
1 error occurred:
        * mixin execution failed: package command failed /cnab/app/cnab/app/mixins/exec/runtimes/exec-runtime install
error running command /cnab/app /usr/bin/false ---I AM A SECRET VALU1E---: exit status 1
Error: error running command /cnab/app /usr/bin/false ---I AM A SECRET VALU1E---: exit status 1



1 error occurred:
        * mixin execution failed: package command failed /cnab/app/cnab/app/mixins/exec/runtimes/exec-runtime install
error running command /cnab/app /usr/bin/false ---I AM A SECRET VALU1E---: exit status 1
Error: error running command /cnab/app /usr/bin/false ---I AM A SECRET VALU1E---: exit status 1



1 error occurred:
        * container exit code: 1, message: <nil>
```

## Version
porter v1.1.0 (b50c1899)

### PR DESCRIPTION
**Pull request by kichristensen**
# What does this change
Ensure logs written using the tracer won't contain sensitive information.

# What issue does it fix
closes #3216
closes #2256

# Checklist
- [X] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

[contributors]: https://porter.sh/src/CONTRIBUTORS.md

### CODE REVIEW

File: pkg/portercontext/context.go [hunk 1]
```diff
@@ -451,6 +456,16 @@ func (cw *CensoredWriter) Write(b []byte) (int, error) {
 	return len(b), err
 }
 
+func (cw *CensoredWriter) Censor(b []byte) []byte {
+	for _, val := range cw.sensitiveValues {
+		if strings.TrimSpace(val) != "" {
+			b = bytes.Replace(b, []byte(val), []byte("*******"), -1)
```
Comment (schristoff) [inline pkg/portercontext/context.go:462]: qq: Should we replace `[]byte("*******"),` with just `[]byte("**"),`, assuming we have a very long sensitive value this can get kind of large, no?

**Review by schristoff — APPROVED** [review]
One question, overall looks great. If tests are happy, so am I ;)

File: pkg/portercontext/context.go (hunk 1 above)
Comment (kichristensen) [reply pkg/portercontext/context.go:462]: @schristoff  The length of the sensitive value should not matter, as it will always replace the value with `*******`. This will of course make the log longer if the sensitive value is very short, but otherwise the lenght should not matter
