### PR TITLE
mage: add checksum for published assets

### LINKED ISSUE #1797: Publish checksums
We need to publish checksums along with our release binaries.

One thing to look into is if our build would work with goreleaser yet. When I last tried to move over to goreleaser I ran into like 100 things that we do that doesn't work with it. From the go build, to things like our latest and canary tags. It could be worth cataloging everything that we do that isn't standard and figure out how we could use goreleaser, and still make things like installing the latest release, or the canary easier.

### PR DESCRIPTION
**Pull request by VinozzZ**
Signed-off-by: Yingrong Zhao <yingrong.zhao@gmail.com>

# What does this change
Publish checksums for all assets so users can validate whether the downloaded file has been tempered

# What issue does it fix
Part of the fix for #1797 

[1]: https://porter.sh/src/CONTRIBUTING.md#when-to-open-a-pull-request

# Notes for the reviewer

Since only using checksum doesn't prevent the case when checksum file itself has been tempered, another PR will address that issue by using signing using a private key 

# Checklist
- [ ] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://porter.sh/src/CONTRIBUTORS.md

### CODE REVIEW

File: mage/releases/publish.go [hunk 1]
```diff
@@ -217,3 +231,35 @@ func listFiles(dir string) []string {
 
 	return names
 }
+
+func generateChecksumFile(path string) (string, error) {
+	if filepath.Ext(path) == "sha256sum" {
```
Comment (carolynvs) [inline mage/releases/publish.go:236]: Wouldn't the extension be ".sha256sum"? 🤔

File: mage/releases/publish.go [hunk 2]
```diff
@@ -217,3 +231,35 @@ func listFiles(dir string) []string {
...
+	if _, err := io.Copy(hash, data); err != nil {
+		return "", err
+	}
+	sum := hash.Sum(nil)
+
+	// write the checksum and file name to the checksum file so it can be
+	// verified by tools like `shasum`
+	_, err = f.WriteString(fmt.Sprintf("%x  %s", sum[:], filepath.Base(path)))
+	if err != nil {
+		return "", err
```
Comment (carolynvs) [inline mage/releases/publish.go:261]: Even though this is just our build script, it's still super helpful to wrap the errors from low level calls like what's in this function with `errors.Wrap` and provide context into what we were trying to do when it failed. It helps avoid a build failing with "EOF" or "file not found" without any clue what we were trying to do. 😁

File: mage/releases/publish.go [hunk 3]
```diff
@@ -217,3 +231,35 @@ func listFiles(dir string) []string {
 
 	return names
 }
+
+func generateChecksumFile(path string) (string, error) {
```
Comment (carolynvs) [inline mage/releases/publish.go:235]: Let's add some unit tests for this function so that we can verify that it works. Getting build scripts related to publishing can be tricky and it's no fun to cut a release only to realize that there's a bug in the publish logic. Ask me how I know. 😉

**Review by carolynvs — CHANGES_REQUESTED** [review]
This looks right all my comments are just to help us bring our build scripts up to production code level which is a bit of technical debt that we have been trying to address over time.

File: mage/releases/publish.go (hunk 1 above)
Comment (VinozzZ) [reply mage/releases/publish.go]: You are absolutely right!! Thanks for catching it

File: mage/releases/publish.go (hunk 2 above)
Comment (VinozzZ) [reply mage/releases/publish.go]: I broke down the function into more modular pieces. Let me know if that helps

**Review by carolynvs — APPROVED** [review]
Looks good! I'm going to run the test release pipeline on this to see how it goes
