### PR TITLE
Sanitize archive folder name

### LINKED ISSUE #2151: archive command fails when the bundle name has a slash
## Describe the bug
When I try to archive a bundle that has a slash in the bundle name, archive fails.

## To Reproduce
```console
$ porter archive whalegap.tgz --reference ghcr.io/getporter/examples/whalegap:v0.2.0
Writing logs to /Users/carolynvs/.porter/logs/01G57B1W09P2FB11DQHJYRPBQV.json
Writing logs to /Users/carolynvs/.porter/logs/01G57B1W09P2FB11DQHJYRPBQV.json
Writing logs to /Users/carolynvs/.porter/logs/01G57B1W09P2FB11DQHJYRPBQV.json
Writing logs to /Users/carolynvs/.porter/logs/01G57B1W09P2FB11DQHJYRPBQV.json
mkdir /var/folders/mv/cx7sy9c54wn741p4x6v0_t100000gn/T/examples/whalegap-0.2.0350843934: no such file or directory
```

## Expected behavior
The command should succeed. Seems like the problem is that we are making a directory with the name of the bundle and it's causing a missing parent directory.

Let's fix this by cleaning up the bundle name before using it as a directory name. There may be other allowed characters in a bundle name by the CNAB spec that could also cause trouble when put in a path. Maybe just do a string replace for anything that isn't a-z0-9-_. and turn it into underscores?

## Version
1.0.0-alpha.20

### PR DESCRIPTION
**Pull request by VinozzZ**
# What does this change

Currently, porter uses bundle name as part of the temporary archive folder for storing all artifacts and metadata that's needed for archiving a bundle.
The bundle name may contain invalid path characters, which causes `porter archive` to fail.

This PR fixes above issue by sanitizing bundle name to remove non-standard path characters before using it as part of the archive folder path.
If a path separator is present in a bundle name, we will replace them with a dash, `-`

# What issue does it fix
Closes #2151 

[1]: https://porter.sh/src/CONTRIBUTING.md#when-to-open-a-pull-request

# Notes for the reviewer

# Checklist
- [ ] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you change porter.yaml or a storage document record? Update the corresponding schema file.
- [ ] If this is your first pull request, please add your name to the bottom of our [Contributors][contributors] list. Thank you for making Porter better! 🙇‍♀️

# Reviewer Checklist
* Comment with /azp run test-porter-release if a magefile or build script was modified
* Comment with /azp run porter-integration if it's a non-trivial PR

[contributors]: https://porter.sh/src/CONTRIBUTORS.md

### CODE REVIEW

File: pkg/porter/archive.go [hunk 1]
```diff
@@ -186,6 +183,27 @@ func (ex *exporter) addImage(image bundle.BaseImage) error {
...
+	tmpDir := filepath.Join(os.TempDir(), filepath.Dir(cleanedPath))
+	if err := ex.fs.MkdirAll(tmpDir, 0744); err != nil {
+		return "", err
+	}
+
+	archiveDir, err := ex.fs.TempDir(tmpDir, filepath.Base(cleanedPath))
+	if err != nil {
+		return "", err
+	}
+	if err := ex.fs.Chmod(archiveDir, 0744); err != nil {
```
[the remark this answers is not in the document]
Comment (VinozzZ) [reply pkg/porter/archive.go]: I changed the handling logic and it should make more sense now

File: pkg/porter/archive.go [hunk 2]
```diff
@@ -186,6 +183,27 @@ func (ex *exporter) addImage(image bundle.BaseImage) error {
 	return checkDigest(image, dig)
 }
 
+// createArchiveFolder set up a temporary directory for storing all data needed to archive a bundle.
+// It sanitizes the name and make sure only the current user has full permission to it.
+// If the name contains a path separator, all transit paths are created.
+func (ex *exporter) createArchiveFolder(name string) (string, error) {
+	cleanedPath := afero.UnicodeSanitize(name)
+	tmpDir := filepath.Join(os.TempDir(), filepath.Dir(cleanedPath))
```
[the remark this answers is not in the document]
Comment (VinozzZ) [reply pkg/porter/archive.go]: The reason why I couldn't directly use the `TmpDir` is because it doesn't create nested folders. I changed the function to replace all path separators to a dash. Let me know what do u think

[the remark this answers is not in the document]
Comment (carolynvs) [reply pkg/porter/archive.go]: That sounds like a good way to deal with it, thanks! 👍

File: pkg/porter/archive_test.go [hunk 3]
```diff
@@ -51,3 +52,18 @@ func TestArchive_Validate(t *testing.T) {
...
+	p := NewTestPorter(t)
+	defer p.Close()
+	ex := exporter{
+		fs: p.FileSystem,
+	}
+
+	dir, err := ex.createArchiveFolder("examples/test-bundle-0.2.0")
+	require.NoError(t, err)
+
+	info, err := ex.fs.Stat(dir)
```
Comment (carolynvs) [inline pkg/porter/archive_test.go:66]: Can you add one more assert that checks the name created? That will help check for replacing the path seperator with a dash.

**Review by carolynvs — CHANGES_REQUESTED** [review]
Looks great! I just have one suggestion for better test coverage and we are all set!

File: pkg/porter/archive_test.go [hunk 4]
```diff
@@ -51,3 +52,18 @@ func TestArchive_Validate(t *testing.T) {
...
+	require.NoError(t, err)
+	require.Equal(t, pkg.FileModeDirectory.String(), info.Mode().Perm().String(), dir)
```
Comment (carolynvs) [inline pkg/porter/archive_test.go:68]: We also have a test helper that gives you a better error message whe comparing file modes 

```
import "get.porter.sh/porter/tests"

... 

tests.AssertDirectoryPermissionsEqual(...)
```

Comment (carolynvs) [reply pkg/porter/archive_test.go:68]: You don't have to change the code to use it, I just wanted you to be aware of the helpers since they are spread out. We really should consolidate them eventually! 😅

Comment (VinozzZ) [reply pkg/porter/archive_test.go]: Oh, I did not notice we have this nice helper function. Thank your for mentioning it. I just changed to use this helper funcion cuz it's so nice

**Review by carolynvs — APPROVED** [review]
Thanks for fixing this! 🎉
